# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b30b333f22f53d4e067f31eb3f1eb858f18246e4fe8a461ff64e776d8e2f849baaa06d4463faa5be68ac0543db882f8b4eae908af1171c0315aa171f40f65341

test:
  secret_key_base: 4a75cb4d8467cac0ff097d8102f04a069e3d71caea7e4c122afcb79014b9531e68f617e8ddaa2d2df693ecde7684f22c4bca93cef22c76e395ff614e1e38d722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
